kind: Service                             
apiVersion: v1
metadata:
  name: k8slab
  labels:
    app: k8slab
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: k8slab                    
  type: LoadBalancer                   
